---
- name: Deploy Laravel Application
  hosts: localhost
  tasks:
    - name: Ensure the Laravel project directory exists
      file:
        path: ~/Movers
        state: directory

    - name: Print current working directory
      command: pwd
      register: pwd_output

    - name: Display current directory
      debug:
        msg: "Current working directory: {{ pwd_output.stdout }}"

    - name: List files in the current directory
      command: ls -la
      register: ls_output

    - name: Display files
      debug:
        msg: "{{ ls_output.stdout }}"

    - name: List files in the parent directory
      command: ls -la ..
      register: parent_ls_output

    - name: Display files in parent directory
      debug:
        msg: "Files in parent directory: {{ parent_ls_output.stdout }}"

    - name: Copy application files
      copy:
        src: ../app  # Adjust this based on where your application files are
        dest: ~/Movers
        owner: $USER
        mode: '0755'

    - name: Run Laravel migrations
      command: php artisan migrate --force
      args:
        chdir: ~/Movers
