---
- name: Deploy Laravel Application
  hosts: localhost  # Adjusted to 'localhost' for running locally
  tasks:
    - name: Ensure the Laravel project directory exists
      file:
        path: ~/Movers  # Ensure this is the intended path
        state: directory

    - name: Copy application files
      copy:
        src: ./Movers  # Ensure this path is correct and files exist
        dest: ~/Movers
        owner: $USER  # Use the current user
        mode: '0755'

    - name: Run Laravel migrations
      command: php artisan migrate --force
      args:
        chdir: ~/Movers  # Ensure this matches your project structure

    # Add additional tasks as needed
