---
- name: Deploy Laravel Application
  hosts: localhost
  tasks:
    - name: Ensure the Laravel project directory exists
      file:
        path: ~/Movers
        state: directory

    - name: Copy application files
      copy:
        src: ~/Movers/  # Adjust based on where your application files are
        dest: ~/Movers
        owner: "{{ ansible_env.USER }}"
        mode: '0755'

    - name: Check if artisan file exists
      stat:
        path: ~/Movers/artisan  # Check for artisan in the destination
      register: artisan_file

    - name: Display artisan file status
      debug:
        msg: "Artisan file exists: {{ artisan_file.stat.exists }}"

    - name: Run Laravel migrations
      command: php artisan migrate --force
      args:
        chdir: ~/Movers  # Ensure this matches your project structure
      when: artisan_file.stat.exists
