---
- name: Deploy Laravel Application
  hosts: localhost  # Adjusted to 'localhost' for running locally
  tasks:
    - name: Ensure the Laravel project directory exists
      file:
        path: ~/Movers  # Ensure this is the intended path
        state: directory

    - name: Print current working directory
      command: pwd
      register: pwd_output

    - name: Display current directory
      debug:
        msg: "Current working directory: {{ pwd_output.stdout }}"

    - name: List files in the current directory
      command: ls -la
      register: ls_output

    - name: Display files
      debug:
        msg: "{{ ls_output.stdout }}"

    - name: Copy application files
      copy:
        src: ./Movers  # Ensure this path is correct and files exist
        dest: ~/Movers
        owner: $USER  # Use the current user
        mode: '0755'

    - name: Run Laravel migrations
      command: php artisan migrate --force
      args:
        chdir: ~/Movers  # Ensure this matches your project structure

    # Add additional tasks as needed
