---
- name: Deploy Laravel Application
  hosts: local
  tasks:
    - name: Ensure the Laravel project directory exists
      file:
        path: ~/laravel_project  # Use a path with write permissions
        state: directory

    - name: Copy application files
      copy:
        src: ./laravel  # Adjust this based on your actual project structure
        dest: ~/laravel_project
        owner: runner  # Adjust owner if necessary
        mode: '0755'

    - name: Run Laravel migrations
      command: php artisan migrate --force
      args:
        chdir: ~/laravel_project  # Adjust path to where your project files are

    # Add additional tasks as needed
